# Generated by Django 5.2 on 2025-04-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shipping', 'shipping'), ('biling', 'billling')], default='shipping')),
                ('adress_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home')),
                ('phonenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('landmark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='users.adress'),
        ),
    ]
