# Generated by Django 5.2 on 2025-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_adress_city_alter_adress_house_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
