# Generated by Django 5.2 on 2025-05-07 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_adress_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='adress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='users.customer'),
        ),
        migrations.AddField(
            model_name='adress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
