# Generated by Django 5.2 on 2025-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'cartstage'), (1, 'pending'), (2, 'procesing'), (3, 'shipped'), (4, 'deliverd'), (5, 'cancelled'), (6, 'refunded')], default=0, max_length=20),
        ),
    ]
