# Generated by Django 5.2 on 2025-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cartstage', 'cartstage'), ('pending', 'pending'), ('processing', 'procesing'), ('shipped', 'shipped'), ('deliverd', 'deliverd'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='cartstage'),
        ),
    ]
