# Generated by Django 5.2 on 2025-05-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=15, unique=True)),
                ('isvalid', models.BooleanField(default=False)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(blank=True, null=True)),
                ('valid_to', models.DateField()),
                ('valid_from', models.DateField()),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('FIXED_AMOUNT', 'FIXED_AMOUNT')])),
                ('percentage_rate', models.IntegerField(blank=True, null=True)),
                ('fixed_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_orders', to='orders.discount'),
        ),
    ]
