# Generated by Django 5.2 on 2025-05-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_discount_order_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='fixed_amount',
        ),
    ]
