# Generated by Django 5.2 on 2025-05-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_discount_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'PERCENTAGE'), ('FIXED', 'FIXED')], default='PERCENTAGE'),
        ),
        migrations.AddField(
            model_name='discount',
            name='fixed_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
