# Generated by Django 5.2 on 2025-05-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_discount_discount_type_discount_fixed_amount'),
        ('users', '0008_remove_customer_address_adress_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('debit_card', 'Debit Card'), ('upi', 'upi'), ('bank_transfer', 'Bank Transfer'), ('cash on delivery', 'cash on delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('refunded', 'refunded'), ('canceled', 'canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('Amount', models.IntegerField()),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='users.adress')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='orders_paym_transac_29fb2b_idx'), models.Index(fields=['status'], name='orders_paym_status_83f434_idx'), models.Index(fields=['user', 'created_at'], name='orders_paym_user_id_22c6d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('overnight', 'Overnight Shipping'), ('international', 'International Shipping'), ('pickup', 'Store Pickup')], default='standard', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready_for_shipment', 'Ready for Shipment'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Delivery Failed')], default='processing', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='users.adress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shippings', to='users.customer')),
            ],
            options={
                'verbose_name_plural': 'Shipping',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='orders_ship_trackin_242f36_idx'), models.Index(fields=['status'], name='orders_ship_status_bc173b_idx'), models.Index(fields=['user', 'created_at'], name='orders_ship_user_id_324221_idx')],
            },
        ),
    ]
