# Generated by Django 5.2 on 2025-05-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_notes_remove_order_shipping_cost_and_more'),
        ('users', '0008_remove_customer_address_adress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='users.adress'),
        ),
    ]
