# Generated by Django 5.2 on 2025-05-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_shipping_notes_alter_shipping_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order_item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order_item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
