# Generated by Django 5.2 on 2025-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_tax_amount_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('debit_card', 'Debit Card'), ('upi', 'upi'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'cash on delivery')], max_length=20),
        ),
    ]
