# Generated by Django 5.2 on 2025-06-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Amount',
        ),
    ]
