# Generated by Django 5.2 on 2025-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
