# Generated by Django 5.2 on 2025-06-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='used_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_orders', to='orders.discount'),
        ),
    ]
