# Generated by Django 5.2 on 2025-04-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/catogary_images')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/catogary_images')),
            ],
            options={
                'verbose_name': 'Catogary',
                'verbose_name_plural': 'Catogaries',
                'db_table_comment': 'Catogaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=65, unique=True)),
                ('price', models.FloatField(max_length=12)),
                ('sale_price', models.FloatField(blank=True, max_length=12, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('stock_status', models.CharField(choices=[('in stock', 'in stock'), ('low stock', 'low stock'), ('out of stock', 'out of stock')], default='in stock')),
                ('weight', models.DecimalField(decimal_places=5, max_digits=6)),
                ('purity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('isfetuerd', models.BooleanField()),
                ('isbestseller', models.BooleanField()),
                ('isnew', models.BooleanField()),
                ('ishallmarked', models.BooleanField()),
                ('image1', models.ImageField(upload_to='media/product_images')),
                ('image2', models.ImageField(upload_to='media/product_images')),
                ('image3', models.ImageField(upload_to='media/product_images')),
                ('image4', models.ImageField(upload_to='media/product_images')),
                ('image5', models.ImageField(upload_to='media/product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catogaris', models.ManyToManyField(related_name='products', to='products.catogaries')),
            ],
            options={
                'verbose_name': 'PRODUCT',
                'verbose_name_plural': 'products',
                'db_table_comment': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'poor'), (2, 'fair'), (3, 'good'), (4, 'verygood'), (5, 'excelent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField()),
                ('is_verifeid_purchaser', models.BooleanField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/product_review')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/product_review')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/product_review')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='users.customer')),
            ],
            options={
                'db_table_comment': 'REVIEWS',
                'ordering': ['-created_at'],
            },
        ),
    ]
