# Generated by Django 5.2 on 2025-04-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catogaries',
            options={'ordering': ['-created_at']},
        ),
    ]
