# Generated by Django 5.2 on 2025-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catogaries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verifeid_purchaser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'poor'), (2, 'fair'), (3, 'good'), (4, 'verygood'), (5, 'excelent')], default=1),
        ),
    ]
