# Generated by Django 5.2 on 2025-05-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'in stock'), ('low_stock', 'low stock'), ('out_of_stock', 'out of stock')], default='in_stock'),
        ),
    ]
