# Generated by Django 5.2 on 2025-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='purity',
            field=models.DecimalField(decimal_places=3, default=18, max_digits=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=65, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
