# Generated by Django 5.2 on 2025-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_image2_alter_products_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
