# Generated by Django 5.2 on 2025-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='low_stock',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
